### ISSUE TITLE
Looking forward to open source code and paper

### ISSUE THREAD

**Issue by diadestiny** [fingerk28/Two-stage-Knowledge-For-Multiple-Adverse-Weather-Removal#2]
thanks for your work, Looking forward to open source code and paper

**Comment by qgh1223** [comment]
Where is train.py file?
Look forward to the complete source code

**Comment by Masofish** [comment]
Dear author，thanks for your work, Looking forward to open source code

**Comment by liwei1101** [comment]
Where is train.py file?
Look forward to the complete source code

**Comment by fingerk28** [comment]
Thank you for your interest in our project! The complete source code and paper link have been uploaded.
